# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-03 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=4)),
                ('purpose', models.CharField(choices=[('FP', 'Forgot Password'), ('AA', 'Activate Account')], max_length=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'userOTP',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=100)),
                ('NAME', models.CharField(max_length=100)),
                ('PASSWORD', models.CharField(max_length=100)),
                ('DEPARTMENT', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='users_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USEREMAIL', models.CharField(max_length=100)),
                ('USERNAME', models.CharField(max_length=100)),
                ('CONTACT', models.CharField(max_length=100)),
                ('BLOOD_GP', models.CharField(max_length=100)),
                ('GENDER', models.CharField(max_length=100)),
                ('AGE', models.IntegerField()),
                ('ADDRESS', models.CharField(max_length=100)),
                ('CITY', models.CharField(max_length=100)),
                ('STATE', models.CharField(max_length=100)),
                ('COUNTRY', models.CharField(max_length=100)),
                ('DONATE_Bf', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users_profile',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userotp',
            unique_together=set([('user', 'purpose')]),
        ),
    ]
