# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-03 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180903_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_profile',
            name='ZIP',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
