# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-06 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_users_profile_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='need_blood_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZIP', models.CharField(max_length=100)),
                ('ADDRESS', models.CharField(max_length=100)),
                ('CITY', models.CharField(max_length=100)),
                ('STATE', models.CharField(max_length=100)),
                ('COUNTRY', models.CharField(max_length=100)),
                ('BLOOD_GP', models.CharField(max_length=100)),
                ('USERNAME', models.CharField(max_length=100)),
                ('CONTACT', models.CharField(max_length=100)),
                ('USEREMAIL', models.CharField(max_length=100)),
                ('DATE', models.CharField(max_length=100)),
                ('LONGITUDE', models.CharField(max_length=100)),
                ('LATITUDE', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'need_blood_user',
            },
        ),
    ]
