# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-07 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_need_blood_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='need_blood_user',
            name='LOOKUP_KEY',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
