# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-08 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_active_campaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_campaigns',
            name='COUNTRY',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
