# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-08 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_active_campaigns_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_campaigns',
            name='CAMPAIGN_ID',
        ),
    ]
