# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-08 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_active_campaigns_campaign_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='active_campaigns',
        ),
    ]
