# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-03 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donor_predict',
            fields=[
                ('OP_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('AGE', models.IntegerField()),
                ('OCCUPATION', models.CharField(max_length=100)),
                ('GENDER', models.CharField(max_length=100)),
                ('MARRIED', models.CharField(max_length=100)),
                ('CITY', models.CharField(max_length=100)),
                ('COUNTRY', models.CharField(max_length=100)),
                ('CHANNEL', models.CharField(max_length=100)),
                ('CONTACT', models.CharField(max_length=100)),
                ('EMAIL', models.CharField(max_length=100)),
                ('EDU_LEVEL', models.CharField(max_length=100)),
                ('FAMILY_MEM', models.CharField(max_length=100)),
                ('TOTAL_HISTORICAL_DON', models.CharField(max_length=100)),
                ('LAST_DONATED', models.CharField(max_length=100)),
                ('OTHER_DONATION', models.CharField(max_length=100)),
                ('WEIGHT', models.FloatField()),
                ('HEIGHT', models.FloatField()),
                ('BLOOD_GROUP', models.CharField(max_length=100)),
                ('NET_SCORE', models.FloatField()),
                ('NET_RANK', models.IntegerField()),
                ('TARGET_STATUS', models.CharField(max_length=100)),
            ],
        ),
    ]
