# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-05 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blood_bank_master',
            fields=[
                ('BLOOD_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('HOSPITAL_ID', models.IntegerField()),
                ('DONOR_OP_ID', models.IntegerField()),
                ('BLOOD_QTY', models.IntegerField()),
                ('DONATION_DATE', models.CharField(max_length=100)),
                ('DONATION_TIME', models.CharField(max_length=100)),
                ('BLOOD_STATUS', models.CharField(max_length=100)),
                ('SYSPHILIS', models.CharField(max_length=100)),
                ('HIV_POS', models.CharField(max_length=100)),
                ('HEPATITUS_POS', models.CharField(max_length=100)),
                ('OTHER_DISEASE', models.CharField(max_length=100)),
                ('BLOOD_COLL_METHOD', models.CharField(max_length=100)),
                ('BLOOD_DON_TYPE', models.CharField(max_length=100)),
                ('BLOOD_INTEND_USE', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hospital_info',
            fields=[
                ('HOSPITAL_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('CHAIN_ID', models.IntegerField()),
                ('HOSPITAL_NAME', models.CharField(max_length=100)),
                ('CHAIN_NAME', models.CharField(max_length=100)),
                ('ZIP', models.CharField(max_length=100)),
                ('ADDRESS', models.CharField(max_length=100)),
                ('CITY', models.CharField(max_length=100)),
                ('STATE', models.CharField(max_length=120)),
                ('COUNTRY', models.CharField(max_length=100)),
                ('LONGITUDE', models.CharField(max_length=100)),
                ('LATITUDE', models.CharField(max_length=100)),
                ('CONTACT_NO', models.CharField(max_length=100)),
                ('EMAIL', models.CharField(max_length=100)),
                ('HOSPITAL_OWNERSHIP', models.CharField(max_length=100)),
                ('HOSPITAL_TYPE', models.CharField(max_length=100)),
                ('BLOOD_COLL_FACILITY', models.CharField(max_length=100)),
                ('APositive', models.IntegerField()),
                ('ABPositive', models.IntegerField()),
                ('OPositive', models.IntegerField()),
                ('BPositive', models.IntegerField()),
                ('ANegative', models.IntegerField()),
                ('ABNegative', models.IntegerField()),
                ('ONegative', models.IntegerField()),
                ('BNegative', models.IntegerField()),
                ('TOTAL_BEDS', models.IntegerField()),
                ('SPECIALITY', models.CharField(max_length=100)),
                ('STAFF_COUNT', models.IntegerField()),
                ('DOCTOR_COUNT', models.IntegerField()),
                ('FOOTFALL', models.IntegerField()),
            ],
        ),
    ]
