# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_blood_bank_master_hospital_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_bank_master',
            name='BLOOD_QTY',
            field=models.FloatField(),
        ),
    ]
