# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20180906_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_bank_master',
            name='DONOR_OP_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.donor_predict'),
        ),
        migrations.AlterField(
            model_name='blood_bank_master',
            name='HOSPITAL_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital_info'),
        ),
    ]
