# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20180908_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor_predict',
            name='ADDRESS',
            field=models.CharField(default='Blanding', max_length=100),
        ),
        migrations.AddField(
            model_name='donor_predict',
            name='LATITUDE',
            field=models.CharField(default='37.5617', max_length=100),
        ),
        migrations.AddField(
            model_name='donor_predict',
            name='LONGITUDE',
            field=models.CharField(default='109.4259', max_length=100),
        ),
        migrations.AddField(
            model_name='donor_predict',
            name='STATE',
            field=models.CharField(default='Utah', max_length=120),
        ),
        migrations.AddField(
            model_name='donor_predict',
            name='ZIP',
            field=models.CharField(default='84511', max_length=100),
        ),
    ]
