# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20180909_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_info',
            name='ABNegativeExpected',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='hospital_info',
            name='ABPositiveExpected',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='hospital_info',
            name='ANegativeExpected',
            field=models.IntegerField(default=13),
        ),
        migrations.AddField(
            model_name='hospital_info',
            name='APositiveExpected',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='hospital_info',
            name='BNegativeExpected',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='hospital_info',
            name='BPositiveExpected',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='hospital_info',
            name='ONegativeExpected',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='hospital_info',
            name='OPositiveExpected',
            field=models.IntegerField(default=12),
        ),
    ]
